[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
ticketing_system = "2vPTZ9iRydqA3mbkkK6CPXhFuTBdVc8s3otKmfcABiVK"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
